services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Europe/Amsterdam
    volumes:
      - n8n_data:/home/node/.n8n

  # ollama:
  #   container_name: ollama
  #   restart: unless-stopped
  #   image: ollama/ollama:latest
  #   ports:
  #     - 11434:11434
  #   environment:
  #     - OLLAMA_KEEP_ALIVE=24h
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

volumes:
  n8n_data:
  ollama_data:
